pipeline:
  name: Harness Take Home
  identifier: Harness_Take_Home
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Git_source_repository
        repoName: go-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: HarnessTakeHomeBuild
        identifier: HarnessTakeHomeBuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Unit Test
                  identifier: Run_1
                  spec:
                    connectorRef: GCR
                    image: us.gcr.io/harness-take-home/harness-image:latest
                    shell: Sh
                    command: |-
                      set +e
                      go get gotest.tools/gotestsum
                      gotestsum --format=standard-verbose --junitfile unit-tests.xml
                      exit 0
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
              - step:
                  type: Run
                  name: Build app
                  identifier: Build_app
                  spec:
                    connectorRef: GCR
                    image: gcr.io/harness-take-home/harness-image:latest
                    shell: Sh
                    command: |-
                      set +e
                      gotest gotest.tools/gotestsum
                      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo
                      exit 0
              - step:
                  type: BuildAndPushGCR
                  name: BuildAndPushGCR_1
                  identifier: BuildAndPushGCR_1
                  spec:
                    connectorRef: GCR
                    host: gcr.io
                    projectID: harness-take-home
                    imageName: harness-image
                    tags:
                      - latest
