pipeline:
  name: Harness Take Home
  identifier: Harness_Take_Home
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Git_source_repository
        repoName: go-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: HarnessTakeHomeBuild
        identifier: HarnessTakeHomeBuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Unit Test
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: harness-image
                    shell: Sh
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
              - step:
                  type: Run
                  name: Build app
                  identifier: Build_app
                  spec:
                    connectorRef: account.harnessImage
                    image: harness-image
                    shell: Sh
